### ISSUE TITLE
Format files

### ISSUE THREAD

**Issue by Gunter-Q12** [Polusummator/Help2#1]
- [x] quick-pow
- [x] bit-operations
- [x] f-Euler
- [x] gcdex
- [x] eratosthenes-sieve
- [x] check-for-simplicity
- [x] factorize
- [x] gcd-lcm
- [x] ncr
- [x] date-time
- [x] ~combinations-enumeration~
- [x] two-pointers
- [x] testing
- [x] binsearch
- [x] fractional-cascading
- [x] ternary-search
- [x] #2
- [x] hashes
- [x] z-function
- [x] prefix-function
- [x] Manacher
- [x] trie
- [x] ~suffix-automaton~
- [x] Huffman
- [x] LCS
- [x] LIS
- [x] LCIS
- [x] knapsack
- [x] Levenshtein
- [x] cht-opt
- [x] matrix-opt
- [x] mitm
- [x] heap
- [x] segment-tree
- [x] persistent-st
- [x] sparse-table
- [x] sqrt-decomposition
- [x] Mo
- [x] dsu
- [x] mergesort-tree
- [x] segment-tree-2Dproblems
- [x] pref-sum
- [x] Fenwick
- [x] treap
- [x] implicit-treap
- [x] dfs
- [x] bfs
- [x] Ford-Bellman
- [x] Floyd
- [x] Dijkstra
- [x] mst
- [x] top-sort
- [x] condensation
- [x] two-sat
- [x] euler
- [x] bridges-cutpoints
- [x] lca
- [x] maxmatch
- [x] Kuhn
- [x] Hamilton
- [x] geometry

**Comment by Polusummator** [comment]
Done
